#!/usr/bin/env bash
# Dead-skill detector. Aggregates trace data over the past N days and
# surfaces skills + local scripts that haven't been invoked in that
# window. Retire-candidate signal.
#
# Usage:
#   bash scripts/dead-skill-check.sh              # last 14 days (default)
#   bash scripts/dead-skill-check.sh 30           # custom window
#
# Writes workspace/reports/dead-skills-YYYY-MM-DD.md and prints
# the summary to stdout.
set -uo pipefail

WORKSPACE="/root/.openclaw/workspace"
TRACES="$WORKSPACE/traces"
DAYS="${1:-14}"
TODAY="$(date -u +%F)"
CUTOFF=$(date -u -d "${DAYS} days ago" +%F)
OUT_DIR="$WORKSPACE/reports"
OUT="$OUT_DIR/dead-skills-$TODAY.md"

mkdir -p "$OUT_DIR"

# Collect trace files inside the window
TRACE_FILES=()
for f in "$TRACES"/*.jsonl; do
  [ -f "$f" ] || continue
  date_part=$(basename "$f" .jsonl)
  [[ "$date_part" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || continue
  if [[ ! "$date_part" < "$CUTOFF" ]]; then
    TRACE_FILES+=("$f")
  fi
done

if [ ${#TRACE_FILES[@]} -eq 0 ]; then
  echo "dead-skill-check: no trace files in window ($CUTOFF → $TODAY)" >&2
  exit 0
fi

# --- Skill invocations ---
SKILL_COUNTS=$(jq -r 'select(.tool == "Skill") | .class' "${TRACE_FILES[@]}" 2>/dev/null \
  | sort | uniq -c | sort -rn \
  | awk '{printf "| %-30s | %5d |\n", $2, $1}')
[ -z "$SKILL_COUNTS" ] && SKILL_COUNTS="| _no Skill invocations in window_ | 0 |"

# --- Local script invocations (scripts/*.sh called via Bash) ---
# Build inventory
INVENTORY=$(find "$WORKSPACE/scripts" -maxdepth 3 -name '*.sh' -type f -printf '%P\n' | sort)

# Count invocations per script by grepping Bash command content via paths
# field (captured in trace.sh). Falls back to class if paths is empty.
SCRIPT_USAGE=""
while IFS= read -r script; do
  [ -z "$script" ] && continue
  # Match on full relative path in the trace paths array
  count=$(jq -r --arg s "scripts/$script" '
    select(.tool == "Bash") |
    (.paths // []) as $p |
    if ($p | index($s)) then 1 else empty end
  ' "${TRACE_FILES[@]}" 2>/dev/null | wc -l | tr -d ' ')
  SCRIPT_USAGE+="$(printf '| %-40s | %5d |\n' "$script" "$count")"$'\n'
done <<< "$INVENTORY"

DEAD_SCRIPTS=$(printf '%s' "$SCRIPT_USAGE" | awk -F'|' '$3+0 == 0 {print}')
LIVE_SCRIPTS=$(printf '%s' "$SCRIPT_USAGE" | awk -F'|' '$3+0 > 0 {print}' | sort -t'|' -k3 -rn)

[ -z "$DEAD_SCRIPTS" ] && DEAD_SCRIPTS="| _no dead scripts — all inventory invoked in window_ | — |"
[ -z "$LIVE_SCRIPTS" ] && LIVE_SCRIPTS="| _no scripts invoked in window_ | — |"

cat > "$OUT" <<EOF
# Dead-skill check — $TODAY (window: $CUTOFF → $TODAY, $DAYS days)

_Generated by \`scripts/dead-skill-check.sh\`. Scans ${#TRACE_FILES[@]} trace file(s)._

## Skill invocations (from Skill-tool traces)

| Skill                          | Count |
|--------------------------------|-------|
$SKILL_COUNTS

## Local scripts (scripts/*.sh)

### Dead — 0 invocations in window (retire candidates)

| Script                                   | Count |
|------------------------------------------|-------|
$DEAD_SCRIPTS

### Live — invoked at least once

| Script                                   | Count |
|------------------------------------------|-------|
$LIVE_SCRIPTS

---

_Dead-script signal assumes trace.sh \`paths\` field is populated. Scripts
registered only in \`nightly.sh\`/cron may appear "live" via that path; raw
invocation via shell won't be captured if a command bypasses the Bash
tool. Treat this as one input among several, not as ground truth._
EOF

echo "Wrote $OUT"
echo "---"
head -40 "$OUT"
