#!/usr/bin/env bash
# select.sh — SEPL Select step.
# Reads a reflect review sidecar, extracts unchecked next-step candidates and
# hypotheses, scores each via cheap heuristics, writes ranked list to
# reports/select-<date>.md. No LLM call; deterministic.
#
# Usage:
#   scripts/select.sh                # auto-pick newest review sidecar
#   scripts/select.sh <review-file>  # explicit
#
# Exit: 0 ok, 2 nothing to select, 3 input error.
set -euo pipefail

WORKSPACE="/root/.openclaw/workspace"
REPORTS="$WORKSPACE/reports"
TODAY="$(date -u +%Y-%m-%d)"

input="${1:-}"
if [ -z "$input" ]; then
  input=$(ls -t "$REPORTS"/reflect-*-review.md 2>/dev/null | head -1)
fi
if [ -z "$input" ] || [ ! -f "$input" ]; then
  echo "select: no review sidecar found (looked at $REPORTS/reflect-*-review.md)" >&2
  exit 3
fi

review_date=$(basename "$input" | sed -E 's/^reflect-([0-9]{4}-[0-9]{2}-[0-9]{2})-review\.md$/\1/')
out="$REPORTS/select-$TODAY.md"

if ! bash "$WORKSPACE/scripts/guards/review-shape.sh" "$input" >&2; then
  echo "select: refusing invalid review sidecar $input" >&2
  exit 3
fi

# Extract unchecked next-step lines:  "- [ ] body"  → keep body.
# Multi-line candidates (continuation indented) are folded onto one line.
mapfile -t raw < <(awk '
  /^[[:space:]]*-[[:space:]]*\[[[:space:]]\][[:space:]]/ {
    if (cur != "") print cur
    sub(/^[[:space:]]*-[[:space:]]*\[[[:space:]]\][[:space:]]+/, "", $0)
    cur = $0; next
  }
  /^[[:space:]]+[^-[:space:]]/ && cur != "" {
    sub(/^[[:space:]]+/, " ", $0); cur = cur $0; next
  }
  /^[[:space:]]*$/ || /^[[:space:]]*-/ || /^#/ {
    if (cur != "") { print cur; cur = "" }
  }
  END { if (cur != "") print cur }
' "$input")

if [ "${#raw[@]}" -eq 0 ]; then
  echo "select: no unchecked '- [ ]' candidates found in $input" >&2
  exit 2
fi

# Cheap scoring heuristics. Each candidate gets:
#   reversibility   — high if it touches scripts/hooks/evals (revertable);
#                     low if it edits memory/SOUL/AGENTS (rule changes).
#   eval_coverage   — high if mentions evals/fixture/grader/regex/judge;
#                     low if it's a pure runtime change with no test surface.
#   token_burn      — high if mentions a number×count pattern ("3×/day",
#                     "Nx", "8/day") or names a deterministic-conversion target.
#   risk            — bumped up if mentions auto-merge, master, force, delete.
score_one() {
  local body="$1"
  local rev=2 cov=2 burn=1 risk=0
  # reversibility
  echo "$body" | grep -qiE '(scripts/|hooks/|evals/|fixture)' && rev=3
  echo "$body" | grep -qiE '(SOUL\.md|AGENTS\.md|MEMORY\.md|memory/|USER\.md)' && rev=1
  # eval coverage
  echo "$body" | grep -qiE '(eval|fixture|grader|regex|judge|harness)' && cov=3
  echo "$body" | grep -qiE '(no eval|untested|manual only)' && cov=1
  # token burn signal
  echo "$body" | grep -qiE '([0-9]+[[:space:]]*[xX×][[:space:]]*/?[[:space:]]*(day|wk|week))' && burn=3
  echo "$body" | grep -qiE '(token.burn|deterministic|repeated|recurring)' && burn=$((burn + 1))
  # risk modifiers
  echo "$body" | grep -qiE '(auto.?merge|force.?push|rm.?-rf|delete[[:space:]]+[a-z]+\.md|drop[[:space:]]+table)' && risk=2
  echo "$body" | grep -qiE '(audit|measure|count|read.only|dry.run)' && risk=$((risk - 1))
  # composite. weight: burn x2, cov x2, rev x1, then subtract risk.
  local total=$(( burn * 2 + cov * 2 + rev - risk ))
  printf "%d\t%d\t%d\t%d\t%d\n" "$total" "$burn" "$cov" "$rev" "$risk"
}

slugify() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
    | cut -c1-50
}

# Score every candidate, sort desc, take top N.
N="${SELECT_N:-3}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
i=0
for body in "${raw[@]}"; do
  scores=$(score_one "$body")
  total=$(echo "$scores" | cut -f1)
  rest=$(echo "$scores" | cut -f2-)
  slug=$(slugify "$body")
  printf "%d\t%d\t%s\t%s\t%s\n" "$total" "$i" "$slug" "$rest" "$body" >> "$tmp"
  i=$((i + 1))
done

# header
{
  echo "# Select — $TODAY"
  echo
  echo "_Generated by \`scripts/select.sh\` from \`$(basename "$input")\` (review of $review_date)._"
  echo "_SEPL step 2/5. Heuristic scoring; no LLM call. Top $N candidates by composite score._"
  echo
  echo "## Ranked candidates"
  echo
  echo "| Rank | ID | Score | burn | cov | rev | risk | Title |"
  echo "|------|----|-------|------|-----|-----|------|-------|"
  rank=0
  while IFS=$'\t' read -r total idx slug burn cov rev risk body; do
    rank=$((rank + 1))
    [ "$rank" -gt "$N" ] && break
    title=$(echo "$body" | cut -c1-80 | tr -d '|')
    printf "| %d | %s | %d | %d | %d | %d | %d | %s |\n" \
      "$rank" "$slug" "$total" "$burn" "$cov" "$rev" "$risk" "$title"
  done < <(sort -k1,1 -nr "$tmp")
  echo
  echo "## Candidate detail"
  echo
  rank=0
  while IFS=$'\t' read -r total idx slug burn cov rev risk body; do
    rank=$((rank + 1))
    [ "$rank" -gt "$N" ] && break
    echo "### $rank. \`$slug\`  (score=$total)"
    echo
    echo "**Original line:**"
    echo
    echo "> $body"
    echo
    echo "- token_burn=$burn, eval_coverage=$cov, reversibility=$rev, risk=$risk"
    echo "- next: \`scripts/improve.sh $(basename "$0" .sh | sed 's/^select/select/')-$TODAY $slug\`"
    echo
  done < <(sort -k1,1 -nr "$tmp")
  echo "---"
  echo
  echo "_Total raw candidates considered: ${#raw[@]}_"
  echo "_Source: ${input}_"
} > "$out"

echo "wrote $out (top $N of ${#raw[@]} candidates from $(basename "$input"))"
